//
//  Label.swift
//  Sia&Apao
//
//  Created by Abdiel Soto on 10/14/16.
//  Copyright © 2016 SmartDev. All rights reserved.
//

import ObjectMapper
import RealmSwift

class Label: Object, Mappable {

    var scene_bubbles_text1 = "But before going to bed I need to:"
    var scene_bubbles_text2 = "Have a bubble bath."
    var language = "Language"
    var scene_dress_text4 = "And put my pijamas on."
    var scene_dress_text3 = "Ride the waves with my turtles."
    var scene_brush_teeth_instructions = "Catch the words and put them back into the book"
    var scene_brush_teeth_text2 = "Have a chuckle with Tyro"
    var scene_dress_text2 = "Have a buuble bath."
    var scene_mils_instructions = "Tap on the milk until it's finished"
    var scene_brush_teeth_text3 = "Read a book, like this one!"
    var scene_dress_text1 = "But before going to bed I need to:"
    var scene_brush_teeth_text1 = "But before going to bed I need to:"
    var games = "Games"
    var scene_brush_teeth_text4 = "And brush my teeth."
    var scene_goodnight_galileo_text2 = "Read a book, like this one!"
    var scene_goodnight_galileo_text3 = "Brush my teeth."
    var scene_day_night_instructions = "Pull the sun down and make the moon rise"
    var scene_bubbles_instructions = "Pop the Bubbles"
    var scene_goodnight_galileo_text1 = "But before going to bed I need to:"
    var scene_read_book_text2 = "Drink a big glass of milk."
    var scene_read_book_text1 = "But before going to bed I need to:"
    var scene_read_book_text4 = "And read a book"
    var scene_read_book_text3 = "Have a chuckle with Tyro"
    var scene_turnoff_light_text1 = "But before going to bed I need to:"
    var scene_turnoff_light_text2 = "Get into bed and cuddle Orli"
    var scene_turtles_text1 = "But before going to bed I need to:"
    var scene_turnoff_light_text3 = "Give a kiss good night to my sister."
    var scene_turtles_text2 = "Have a bubble bath."
    var scene_tickle_text3 = "Put my pijamas on."
    var scene_turnoff_light_text4 = "And turn off the light in my room"
    var scene_turtles_text3 = "And ride the waves with my turtles."
    var scene_tickle_text4 = "And giggle just a bit with Waky Jacky"
    var scene_tickle_text1 = "But before going to bed I need to:"
    var scene_cuddle_orli_text4 = "And go into bed and cuddle Orli"
    var scene_day_night_text4 = "Time to go to bed is soon approaching"
    var scene_tickle_text2 = "Ride the waves with my turtles."
    var scene_cuddle_orli_text3 = "Say good night to Galileo"
    var scene_day_night_text3 = "Empty plates are on the sink"
    var scene_day_night_text2 = "I played and laughed with my friends"
    var scene_dance_text4 = "And have a chuckle with Tyro"
    var scene_bed_end_text1 = "The end"
    var favourite_food = "Favourite Food:"
    var scene_dance_text1 = "But before going to bed I need to:"
    var scene_dance_text2 = "Giggle just a bit with Waky Jacky"
    var scene_sleeping_text1 = "The sun has left and moon is up"
    var scene_dance_text3 = "Drink a big glass of milk."
    var scene_day_night_text1 = "The sun has left and the moon is up"
    var scene_sleeping_text3 = "But now is time to go to bed"
    var scene_sleeping_text2 = "I played and laughed with my friends,"
    var scene_goodnight_galileo_text4 = "And say good night to Galileo"
    var scene_cuddle_orli_text2 = "Brush my teeth."
    var scene_cuddle_orli_text1 = "But before going to bed I need to:"
    var favourite_phrase = "Favourite Phrase:"
    var characters = "Characters"
    var scene_dance_instructions = "Dance with Tyro until he gets tier"
    var scene_kiss_apao_text4 = "And give a kiss good night to my sister."
    var scene_dress_instructions = "Help Sia & Apao get dress, tap on the mirror"
    var scene_goodnight_galileo_instructions = "Wave until Galileo goes to his cave"
    var scene_kiss_apao_text3 = "Go into bed and cuddle Orli"
    var scene_kiss_apao_text2 = "Say good night to Galileo"
    var scene_kiss_apao_text1 = "But before going to bed I need to:"
    var scene_sleeping_instructions = "Shhh let them sleep"
    var scene_cuddle_orli_instructions = "See what Orli has to say when you touch his mask"
    var scene_kiss_apao_instructions = "Help Sia kiss Apao"
    var stories = "Stories"
    var scene_turtles_instructions = "Calm the turtles, tap of them"
    var scene_read_book_instructions = "Catch the words and put them back into the book"
    var biography = "Biography"
    var scene_milk_text1 = "But before going to bed I need to:"
    var scene_milk_text3 = "Giggle just a bit with Waky Jacky"
    var scene_milk_text2 = "Put my pijamas on."
    var scene_milk_text4 = "And drink a big glass of milk."
    var scene_tickle_instructions = "Tickle Wacky until she smiles"
    var scene_turnoff_light_instructions = "Turn off the light"
    
}
